#!/bin/bash

function fl8(){
    flake8 --count --show-source .
}

function ban(){
    bandit -r .
}

function aio(){
    fl8
    ban
}

case $1 in
    flake8 ) fl8 ;;
    bandit ) ban ;;
    * ) aio ;;
esac